// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeMind.Data;

#nullable disable

namespace SafeMind.Data.Migrations.DoctorLicensing
{
    [DbContext(typeof(DoctorLicensingDbContext))]
    [Migration("20260207094721_LicenceSpecialtiesAdded")]
    partial class LicenceSpecialtiesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.DoctorLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("NationalId");

                    b.ToTable("DoctorLicenses", (string)null);
                });

            modelBuilder.Entity("Data.Models.LicenceDoctorSpecialty", b =>
                {
                    b.Property<int>("DoctorLicenseId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("DoctorLicenseId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("LicenceDoctorSpecialties", (string)null);
                });

            modelBuilder.Entity("Data.Models.LicenceSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LicenceSpecialties", (string)null);
                });

            modelBuilder.Entity("Data.Models.LicenceDoctorSpecialty", b =>
                {
                    b.HasOne("Data.Models.DoctorLicense", "DoctorLicense")
                        .WithMany("DoctorLicenseSpecialties")
                        .HasForeignKey("DoctorLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.LicenceSpecialty", "Specialty")
                        .WithMany("DoctorLicenceSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorLicense");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Data.Models.DoctorLicense", b =>
                {
                    b.Navigation("DoctorLicenseSpecialties");
                });

            modelBuilder.Entity("Data.Models.LicenceSpecialty", b =>
                {
                    b.Navigation("DoctorLicenceSpecialties");
                });
#pragma warning restore 612, 618
        }
    }
}
